// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG0ZNJbDe9fIFurg7ez9-IjpWt3f9FiKo',
    appId: '1:368977360760:web:4f299249076528b696fa8d',
    messagingSenderId: '368977360760',
    projectId: 'liveasy-assign',
    authDomain: 'liveasy-assign.firebaseapp.com',
    storageBucket: 'liveasy-assign.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA68DuCrCAvQE1La3vWHx1fj7Ee5dcV8a8',
    appId: '1:368977360760:android:2c8762019fa2755196fa8d',
    messagingSenderId: '368977360760',
    projectId: 'liveasy-assign',
    storageBucket: 'liveasy-assign.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVreiC4koLek1CFZiQlOMH8N3oHUUD2iE',
    appId: '1:368977360760:ios:a0afb489e224753b96fa8d',
    messagingSenderId: '368977360760',
    projectId: 'liveasy-assign',
    storageBucket: 'liveasy-assign.appspot.com',
    iosClientId: '368977360760-4vv12qug8c8ueam1kfos546vna6l17o1.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveasyAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVreiC4koLek1CFZiQlOMH8N3oHUUD2iE',
    appId: '1:368977360760:ios:a0afb489e224753b96fa8d',
    messagingSenderId: '368977360760',
    projectId: 'liveasy-assign',
    storageBucket: 'liveasy-assign.appspot.com',
    iosClientId: '368977360760-4vv12qug8c8ueam1kfos546vna6l17o1.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveasyAssignment',
  );
}
